spring:
  application:
    name: ai-code
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/ai_code
    username: XXX
    password: XXX
  profiles:
    active: local
  # redis
  data:
    redis:
      host: xxx.xxx.xxx.xxx
      port: 6379
      password:
      ttl: 3600
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # HTTP客户端连接超时
  web:
    client:
      connection-timeout: 300,000   # 5分钟
      read-timeout: 300,000         # 5分钟
# mybatis-flex配置
mybatis-flex:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      timeout: PT5M
      log-requests: true
      log-responses: true

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.dorr.aicode.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志配置
logging:
  level:
    # Spring Web 请求日志
    org.springframework.web: debug
    # MyBatis SQL 日志
    com.dorr.aicode.mapper: debug

# 添加 oss 对象存储配置
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: 你的AccessKeyID
    access-key-secret: 你的AccessKeySecret
    bucket-name: 你的Bucket名称
    # 文件外网访问域名
    domain: https://你的Bucket名称.oss-cn-hangzhou.aliyuncs.com
    # 如果是新Bucket需要开启V4签名，配置region
    region: cn-hangzhou

# Pexels 图片搜索配置
pexels:
  api-key: <Your API Key>

# 阿里云 DashScope 配置
dashscope:
  api-key: <Your API Key>
  image-model: wan2.2-t2i-flash
