spring:
  application:
    name: ai-code
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.150.101:3306/ai_code
    username: root
    password: itcast321bca
# mybatis-flex配置
mybatis-flex:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.dorr.aicode.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志配置
logging:
  level:
    # Spring Web 请求日志
    org.springframework.web: debug
    # MyBatis SQL 日志
    com.dorr.aicode.mapper: debug