spring:
  application:
    name: ai-code
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://XXX.XXX.XXX.XXX:3306/ai_code
    username: XXX
    password: XXX
  profiles:
    active: local
# mybatis-flex配置
mybatis-flex:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8123
  servlet:
    context-path: /api

# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.dorr.aicode.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 日志配置
logging:
  level:
    # Spring Web 请求日志
    org.springframework.web: debug
    # MyBatis SQL 日志
    com.dorr.aicode.mapper: debug